# Generated by Django 5.2.1 on 2025-05-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
