# Generated by Django 5.2.1 on 2025-06-30 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_order_status_orderaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderaddress',
            name='order',
        ),
    ]
