# Generated by Django 5.2.1 on 2025-06-27 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('store', '0002_alter_orderitem_original_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_order', to='store.order'),
        ),
    ]
