# Generated by Django 5.2.1 on 2025-07-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payments_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='status',
            field=models.CharField(default='delivered', max_length=20),
        ),
    ]
