# .github/workflows/render-ping.yml

name: Daily Render Ping

on:
  schedule:
    # Midnight IST (18:30 UTC previous day)
    - cron: '30 18 * * *'
    # Noon IST (06:30 UTC)
    - cron: '30 6 * * *'
  workflow_dispatch:

jobs:
  curl-website:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render Website
        run: curl -I https://ecommerce-cs19.onrender.com/
